Implement gridadmin.cells.transform
nens/threedigrid pull request #123
Opened 2021-03-24 15:05 UTC by caspervdw

2021-03-24 15:27 UTC, martijn-siemerink requested changes

2021-03-24 15:27 UTC, martijn-siemerink commented on threedigrid/admin/nodes/models.py
> +        self.dx = grid_attrs["dx"].value
This will not be backwards compatible with "old" gridadmins. @jpprins1 Is this a problem? 
I don't expect this to be a problem, since it is only used server side or in threedi_depth, which we control

2021-03-24 16:18 UTC, caspervdw commented on threedigrid/admin/nodes/models.py
> +        self.dx = grid_attrs["dx"].value
This change is actually a leftover from a previous version. I reverted this.

2021-03-24 16:24 UTC, martijn-siemerink approved these changes

2021-03-25 10:06 UTC, jpprins1 commented on threedigrid/admin/nodes/models.py
> +        self.dx = grid_attrs["dx"].value
Note: Don't use .value this does not work in h5py 3.10!

@martijn-siemerink: don't think other people are using this, correct.

2021-03-25 10:08 UTC, jpprins1 commented on threedigrid/admin/gridadmin.py
> +            transform = grid_attrs["pixel_geotransform"].value
Watch out with the .value here!! (probably does not work in h5py 3.10)

2021-03-25 10:08 UTC, jpprins1 requested changes
See comment about .value.

2021-03-25 12:47 UTC, caspervdw commented
I redid this PR because with @martijn-siemerink  I concluded it would be much easier to stick to the current "geotransform" of the pixel coordinates, that is, (dxp, 0, x0p, 0, dxp, y0p).  So with a positive y axis (rasters will need to be flipped).

This is backwards compatible and does not require the fallback logic.

Also it enables us to easily align "windows" to the grid cells later.

2021-03-29 09:02 UTC, merged